content = open('timeforge_backend/settings.py', 'rb').read()
content = content.replace(b'\xc3\xb3', b'o')
content = content.replace(b'\xc3\xb1', b'n')
content = content.replace(b'\xc3\xa9', b'e')
content = content.replace(b'\xc3\xa1', b'a')
content = content.replace(b'\xc3\xad', b'i')
content = content.replace(b'\xc3\xba', b'u')
open('timeforge_backend/settings.py', 'wb').write(content)
print('Listo')