# Generated by Django 6.0.3 on 2026-04-12 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tiempo_estimado', models.IntegerField()),
                ('tiempo_real', models.IntegerField(default=0)),
                ('completada', models.BooleanField(default=False)),
            ],
        ),
    ]
