# Generated by Django 6.0.3 on 2026-04-12 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='tiempo_estimado',
            new_name='estimated_time',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='completada',
            new_name='is_completed',
        ),
        migrations.RenameField(
            model_name='tarea',
            old_name='titulo',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='tarea',
            name='tiempo_real',
        ),
        migrations.AddField(
            model_name='tarea',
            name='actual_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
