# Generated by Django 6.0.2 on 2026-04-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_usertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='last_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
